name: "Antora Site"
description: "Generate the Antora site"
branding:
  icon: book-open
  color: pink
inputs:
  antora_playbook:
    description: 'The Antora playbook file'
    required: true
    default: 'site.yaml'
  site_sources_path:
    description: 'The path relative to workspace root, where the asciidoc sources exits'
    required: false
  branch:
    description: 'The branch to push the generated site to'
    required: true
    default: 'gh-pages'
  credentials:
    description: 'Git Credentials for accessing docs in other repos'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
     - ${{ inputs.antora_playbook}}
     - ${{ inputs.site_sources_path }}
     - ${{ inputs.branch }}
     - ${{ inputs.credentials }}
